# Generated by Django 4.2 on 2023-04-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='service_provider',
        ),
    ]
